#!/usr/bin/env python

"""
DnaChisel Command Line Interface

Usage:
  dnachisel <source> <target>

Where ``source`` is a fasta or Genbank file, and target can be one of:
- A folder name or a zip name (extension .zip). In this case a complete report
  along with the sequence will be generated.
"""


if __name__ == "__main__":
    pass